version: '3'

volumes:
  data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4800:80"
    volumes:
      - ./:/var/www/html # Mount the current directory to /var/www/html for dev purposes
    #        - data:data # Mount the data volume to /var/www/html/data for prod purposes
    restart: always